"""The claim->fact validator (MOO-419, P0-2).

CS-1 is the happy path; CS-3's strictness probe is the one that matters. Both
run offline against pure functions — no chat(), no provider, $0.
"""

from __future__ import annotations

import dataclasses

import pytest
from fixtures import cs1_blocks, cs1_story

from newsdesk.claims import Claim, ScriptBlock, validate_script
from newsdesk.facts import Source, Story


# --- CS-1: the happy path ---------------------------------------------------


def test_cs1_script_passes():
    result = validate_script(cs1_story(), cs1_blocks())
    assert result.passed, result.explain()


def test_cs1_every_fact_is_used_by_some_block():
    """No orphan facts — the acceptance criterion is F1-F6 with no orphans."""
    used = {c.fact_id for b in cs1_blocks() for c in b.claims}
    assert used == {f.id for f in cs1_story().facts}


# --- CS-3: strictness -------------------------------------------------------


def test_number_with_no_claim_is_rejected():
    """The CS-3 probe: a narration number that traces to nothing."""
    story = cs1_story()
    bad = ScriptBlock(
        n=1,
        role="cold open",
        narration=(
            "Thirty-one percent of your dollar goes to policing. That share has "
            "grown quietly for years, and nobody voted on it."
        ),
        claims=(),
    )
    result = validate_script(story, (bad,))
    assert not result.passed
    assert "thirty-one" in result.explain().lower()


def test_rejection_names_the_offending_claim():
    story = cs1_story()
    bad = ScriptBlock(
        n=2,
        role="stakes",
        narration="Ninety percent of stations went dark. Nobody counted them.",
        claims=(),
    )
    assert "ninety" in validate_script(story, (bad,)).explain().lower()


def test_unknown_fact_id_is_rejected():
    story = cs1_story()
    block = ScriptBlock(
        n=1,
        role="cold open",
        narration="One point one billion dollars vanished. It had been approved.",
        claims=(Claim(spoken="One point one billion dollars", fact_id="F9", evidence="$1.1B"),),
    )
    result = validate_script(story, (block,))
    assert not result.passed
    assert "F9" in result.explain()


def test_evidence_absent_from_the_cited_fact_is_rejected():
    """Citing a real fact that does not actually say it is the subtler failure."""
    story = cs1_story()
    block = ScriptBlock(
        n=1,
        role="cold open",
        narration="Two point four billion dollars vanished. It had been approved.",
        claims=(Claim(spoken="Two point four billion dollars", fact_id="F1", evidence="$2.4B"),),
    )
    result = validate_script(story, (block,))
    assert not result.passed
    assert "$2.4B" in result.explain()


def test_spoken_phrase_absent_from_the_narration_is_rejected():
    """A mapping that describes a line the script does not contain is not a mapping."""
    story = cs1_story()
    block = ScriptBlock(
        n=1,
        role="cold open",
        narration="Money vanished from public broadcasting. It had been approved.",
        claims=(Claim(spoken="One point one billion dollars", fact_id="F1", evidence="$1.1B"),),
    )
    assert not validate_script(story, (block,)).passed


# --- calibration: the gate must not block legitimate copy -------------------


def test_prose_without_numbers_needs_no_claim():
    """CS-2's lesson: a validator that fires on everything gets switched off."""
    story = cs1_story()
    block = ScriptBlock(
        n=6,
        role="kicker",
        narration=(
            "The tower still stands. What lights it now is smaller, local, and "
            "paid for by the people who happen to live near it."
        ),
        claims=(),
    )
    assert validate_script(story, (block,)).passed


def test_the_cs2_fabrication_is_caught():
    """The line that widened this module's scope, 2026-07-28.

    Generated by the orchestrator's first run on stories/cs2.yaml. Both
    quantities traced perfectly and "records outsold every other physical
    format combined" is in none of the five facts — and nothing objected,
    because the check only ever looked at digits.
    """
    story = Story.build(
        "Vinyl now outsells CDs three to one",
        [("US vinyl revenue passed $1 billion in 2025, reaching $1.04 billion — "
          "the first time since 1983", [Source.citation("RIAA year-end report")])],
    )
    block = ScriptBlock(
        n=1,
        narration=(
            "Vinyl revenue hit one point zero four billion dollars. For the first "
            "time since nineteen eighty-three, records outsold every other "
            "physical format combined."
        ),
        claims=(
            Claim(spoken="one point zero four billion dollars", fact_id="F1",
                  evidence="reaching $1.04 billion"),
            Claim(spoken="first time since nineteen eighty-three", fact_id="F1",
                  evidence="the first time since 1983"),
        ),
    )
    problems = validate_script(story, (block,)).problems
    assert [p.kind for p in problems] == ["unmapped_assertion"]
    assert "records outsold every other physical format combined" in problems[0].message


def test_an_unmapped_assertion_only_fires_where_a_claim_made_the_sentence_load_bearing():
    """The scoping rule, both directions, in one test.

    A sentence with no claim is rhetorical framing and Wall 3's human owns it.
    A sentence carrying a traced number is presenting itself as reporting, so
    anything else riding in it is borrowing that credibility.

    Whole-line coverage was tried first and flagged the CS-1 kicker, which is
    the failure `test_prose_without_numbers_needs_no_claim` was written to
    prevent — a validator that fires on everything gets switched off.
    """
    story = cs1_story()
    unclaimed = ScriptBlock(
        n=6,
        narration="Seventy percent of the staff was gone. The tower still stands.",
        claims=(Claim(spoken="Seventy percent of the staff was gone",
                      fact_id="F3", evidence="CPB cut staff ~70%"),),
    )
    assert validate_script(story, (unclaimed,)).passed, (
        "'The tower still stands' carries no claim and must not be flagged"
    )

    riding = ScriptBlock(
        n=6,
        narration="Seventy percent of the staff was gone and every transmitter fell silent.",
        claims=(Claim(spoken="Seventy percent of the staff was gone",
                      fact_id="F3", evidence="CPB cut staff ~70%"),),
    )
    problems = validate_script(story, (riding,)).problems
    assert [p.kind for p in problems] == ["unmapped_assertion"]
    assert "transmitter fell silent" in problems[0].message


def test_evidence_match_ignores_case_and_spacing():
    """A model that shouts its evidence, or double-spaces it, has still cited it.

    Spans the whole assertion rather than the bare quantity — since 2026-07-28
    a claim that maps only "a third" leaves "Watertown lost ... of its budget"
    tracing to nothing. The property under test here is the case/space
    tolerance in the EVIDENCE comparison, and it is only reachable once the
    block is otherwise clean.
    """
    story = cs1_story()
    block = dataclasses.replace(
        cs1_blocks()[3],
        claims=(
            Claim(
                spoken="Watertown lost a third of its budget",
                fact_id="F4",
                evidence="WPBS   Watertown NY LOST ~$1M   (A  THIRD   of its budget)",
            ),
            Claim(
                spoken="Fairbanks lost one point two million dollars and cut its overnight broadcasts",
                fact_id="F4",
                evidence="KUAC Fairbanks lost $1.2M, cut overnight broadcasts",
            ),
            Claim(
                spoken="West Texas lost forty-eight percent of revenue",
                fact_id="F4",
                evidence="Basin PBS West Texas lost 48% of revenue",
            ),
        ),
    )
    assert validate_script(story, (block,)).passed


@pytest.mark.parametrize(
    "phrase",
    ["fifteen hundred", "seventy percent", "1,500", "48%", "a third", "nineteen sixty-seven"],
)
def test_number_bearing_phrases_are_detected(phrase):
    """If the detector misses these, the CS-3 probe passes vacuously."""
    from newsdesk.claims import number_tokens

    assert number_tokens(phrase), f"{phrase!r} should read as number-bearing"


@pytest.mark.parametrize("phrase", ["the tower still stands", "grants were closed out"])
def test_plain_prose_is_not_number_bearing(phrase):
    from newsdesk.claims import number_tokens

    assert not number_tokens(phrase)
