"""Narration: measurement, the correction ladder, and the TTS chain (MOO-426).

Everything here runs at $0 with no network. The audio fixtures are generated by
ffmpeg at test time rather than committed, so the silence-trim assertions are
made against real waveforms with known lead and tail padding — the one part of
this module that cannot honestly be tested against a mock.
"""

from __future__ import annotations

import asyncio
import subprocess
from pathlib import Path

import pytest

from newsdesk.narration import (
    MAX_REVOICES,
    PAUSE_TAGS,
    NarrationError,
    Take,
    VoiceSpec,
    best_take,
    classify,
    local_path_of,
    narrate,
    paced,
    pause_tag,
    probe_duration,
    run_take,
    sha256_of,
    store_take,
    strip_silence,
    take_window,
    voice_specs,
)

# Three sentences, so there are exactly two internal boundaries and one final
# one that must never receive a pause — a pause after the last sentence is
# trailing silence, and the trim strips it right back off.
LINE = (
    "Three hundred thousand households lost their water subsidy in a single "
    "budget cycle. Nobody announced it. The line item simply stopped appearing."
)

KIT_VOICE = {
    "primary": {
        "provider": "elevenlabs",
        "model": "eleven_v3",
        "voice_id": "6lbtrJXRylVZ6EqIQQPT",
        "voice_name": "Marcus Louis",
    },
    "fallback": {
        "provider": "lmnt",
        "model": "lmnt",
        "voice_id": "nathan",
        "voice_name": "Nathan",
    },
    "delivery": {"target_take_seconds": [9.0, 10.5]},
}


# --- fixtures generated by ffmpeg, so the waveform is real ------------------


def _render(path: Path, segments: list[tuple[str, float]]) -> Path:
    """Build a mono wav from ("silence"|"tone", seconds) segments."""
    parts, labels = [], []
    for i, (kind, seconds) in enumerate(segments):
        # `aevalsrc` spells sample rate `s`; `sine` spells it `r`. Not a typo.
        src = "aevalsrc=0:s=44100" if kind == "silence" else "sine=f=440:r=44100"
        parts.append(f"{src}:d={seconds}[s{i}]")
        labels.append(f"[s{i}]")
    graph = ";".join(parts) + f";{''.join(labels)}concat=n={len(segments)}:v=0:a=1[out]"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-filter_complex", graph,
         "-map", "[out]", str(path)],
        check=True,
    )
    return path


@pytest.fixture
def padded(tmp_path: Path) -> Path:
    """1.0s silence + 3.0s tone + 1.5s silence = 5.5s, 3.0s of which is signal."""
    return _render(tmp_path / "padded.wav",
                   [("silence", 1.0), ("tone", 3.0), ("silence", 1.5)])


@pytest.fixture
def internal_pause(tmp_path: Path) -> Path:
    """Padding at both ends around a line that pauses in the middle."""
    return _render(
        tmp_path / "internal.wav",
        [("silence", 1.0), ("tone", 1.0), ("silence", 0.8),
         ("tone", 1.0), ("silence", 1.0)],
    )


# --- measurement -----------------------------------------------------------


def test_probe_duration_reads_the_real_length(padded):
    assert probe_duration(padded) == pytest.approx(5.5, abs=0.05)


def test_strip_silence_removes_the_lead_and_the_tail(padded, tmp_path):
    out = strip_silence(padded, tmp_path / "trimmed.wav")
    assert probe_duration(out) == pytest.approx(3.0, abs=0.15)


def test_strip_silence_keeps_the_pause_between_sentences(internal_pause, tmp_path):
    """The one thing the trim must not do.

    voice.json measured sentence-end pauses as what fills the ten-second take —
    the only take that landed in window was the choppy one. A trim that ran
    silenceremove with stop_periods=-1 would strip those too and shorten every
    take by exactly the thing that made it work.
    """
    out = strip_silence(internal_pause, tmp_path / "trimmed.wav")
    assert probe_duration(out) == pytest.approx(2.8, abs=0.2)


def test_probe_duration_refuses_a_file_that_is_not_audio(tmp_path):
    bad = tmp_path / "not-audio.wav"
    bad.write_bytes(b"this is not a waveform")
    with pytest.raises(NarrationError):
        probe_duration(bad)


# --- the window ------------------------------------------------------------


def test_the_window_comes_from_the_brand_kit():
    assert take_window(KIT_VOICE) == (9.0, 10.5)


def test_a_kit_without_a_window_raises_rather_than_defaulting():
    with pytest.raises(NarrationError):
        take_window({"delivery": {}})


@pytest.mark.parametrize(
    ("seconds", "verdict"),
    [(8.99, "short"), (9.0, "in"), (9.8, "in"), (10.5, "in"), (10.51, "long")],
)
def test_classify_against_the_window(seconds, verdict):
    assert classify(seconds, (9.0, 10.5)) == verdict


# --- the correction ladder -------------------------------------------------


def test_pauses_land_between_sentences():
    out = paced(LINE, "[pause]")
    assert out.count("[pause]") == 2


def test_no_pause_is_added_after_the_final_sentence():
    """A trailing pause is trailing silence, and the trim removes it.

    Adding one would cost a take and change nothing measurable.
    """
    assert not paced(LINE, "[pause]").rstrip().endswith("[pause]")


def test_a_single_sentence_is_left_alone():
    one = "Nobody announced it."
    assert paced(one, "[pause]") == one


def test_pacing_does_not_change_the_words():
    spoken = paced(LINE, "[pause]").replace("[pause]", "")
    assert spoken.split() == LINE.split()


@pytest.mark.parametrize(
    ("deficit", "tag"), [(0.15, "[pause]"), (0.5, "[pause]"), (2.4, "[long pause]")]
)
def test_the_notch_is_sized_by_the_deficit(deficit, tag):
    assert pause_tag(deficit, boundaries=1) == tag


def test_every_notch_has_a_measured_gain_behind_it():
    """`[short pause]` was dropped, and this is what stops it coming back.

    It was never measured to buy anything. The spike quantified `[pause]` at
    +0.36s per boundary and `[long pause]` at +1.25s; `[short pause]` sat below
    both by assumption alone, and on the live CS-1 run it twice failed to move a
    0.26s deficit on block 6 — two corrections, $0.07, no change. A notch that
    costs a take and buys nothing measurable is worse than no notch, because it
    consumes one of the two attempts an editor is waiting on.
    """
    assert PAUSE_TAGS == ("[pause]", "[long pause]")


def test_the_notch_is_sized_per_boundary_not_per_take():
    """The same deficit needs a smaller notch when there are more places to put it.

    Measured on eleven_v3: `[pause]` buys about 0.36s at each internal sentence
    boundary and `[long pause]` about 1.25s. So a 0.9s deficit is one `[pause]`
    per boundary across three of them, and a single `[long pause]` across one.
    Sizing against the whole deficit under-fires on a two-sentence block, which
    is exactly how block 6 of the live CS-1 run burned two corrections and
    stayed short.
    """
    assert pause_tag(0.9, boundaries=3) == "[pause]"
    assert pause_tag(0.9, boundaries=1) == "[long pause]"


def test_the_notch_escalates_on_a_second_attempt():
    """A first correction that undershot should not be repeated identically."""
    first = pause_tag(0.15, boundaries=1)
    second = pause_tag(0.15, boundaries=1, bump=1)
    assert PAUSE_TAGS.index(second) == PAUSE_TAGS.index(first) + 1


def test_the_notch_stops_at_the_longest_pause():
    assert pause_tag(3.0, boundaries=1, bump=5) == PAUSE_TAGS[-1]


# --- keeping the closest take ----------------------------------------------


def _take(n: int, seconds: float) -> Take:
    return Take(n=n, duration_s=seconds, status="review")


def test_a_take_inside_the_window_wins():
    takes = [_take(1, 8.0), _take(1, 9.5), _take(1, 12.0)]
    assert best_take(takes, (9.0, 10.5)).duration_s == 9.5


def test_the_closest_miss_wins_when_none_land():
    """Three attempts that all missed still produce the best available take.

    Discarding a 10.7s take because it missed by 0.2s, and keeping the 6.0s one
    that happened to come last, would be worse than not correcting at all.
    """
    takes = [_take(1, 6.0), _take(1, 10.7), _take(1, 8.2)]
    assert best_take(takes, (9.0, 10.5)).duration_s == 10.7


def test_best_take_of_nothing_is_nothing():
    assert best_take([], (9.0, 10.5)) is None


# --- voice specs -----------------------------------------------------------


def test_the_chain_is_read_from_the_published_kit():
    primary, fallback = voice_specs(KIT_VOICE)
    assert (primary.provider, primary.model) == ("elevenlabs", "eleven_v3")
    assert (fallback.provider, fallback.voice_id) == ("lmnt", "nathan")


def test_a_kit_missing_the_primary_voice_raises():
    with pytest.raises(NarrationError):
        voice_specs({"fallback": KIT_VOICE["fallback"]})


def test_a_kit_missing_a_voice_id_raises():
    """A voice id that silently defaults is a different narrator, undisclosed."""
    broken = {**KIT_VOICE, "primary": {"provider": "elevenlabs", "model": "eleven_v3"}}
    with pytest.raises(NarrationError):
        voice_specs(broken)


def test_only_eleven_v3_advertises_pause_tags():
    """The lever is model-specific and was measured, not assumed.

    ElevenLabs documents SSML break tags on every model EXCEPT v3, and audio
    tags — [pause], [short pause], [long pause] — on v3. LMNT has neither. A
    provider that gets the wrong vocabulary reads the tag out loud.
    """
    primary, fallback = voice_specs(KIT_VOICE)
    assert primary.pause_tags is True
    assert fallback.pause_tags is False


# --- the chain, walked by us -----------------------------------------------


class FakeVoice:
    """A TTS provider that renders takes of scripted length, at $0.

    Returns real audio, so the take that comes back out is measured by the same
    ffprobe path a live run uses rather than by a number handed to the assertion.
    """

    def __init__(self, tmp_path: Path, script):
        self.tmp_path = tmp_path
        self.script = list(script)
        self.calls: list[tuple[str, str]] = []

    def __call__(self, spec: VoiceSpec, text: str):
        self.calls.append((spec.provider, text))
        outcome = self.script.pop(0) if self.script else 3.0
        if isinstance(outcome, Exception):
            raise outcome
        path = _render(
            self.tmp_path / f"take-{len(self.calls)}.wav",
            [("silence", 0.4), ("tone", outcome), ("silence", 0.6)],
        )
        return path, 0.03


def _run(voice, *, specs, window=(9.0, 10.5), narration=LINE, **kw):
    return asyncio.run(
        run_take(1, narration, specs=specs, window=window, speak=voice,
                 sleep=_no_wait, **kw)
    )


async def _no_wait(_seconds: float) -> None:
    """Backoff is real in production and instant here."""
    return None


@pytest.fixture
def specs():
    return list(voice_specs(KIT_VOICE))


def test_a_take_in_window_is_ready_on_the_primary(tmp_path, specs):
    take = _run(FakeVoice(tmp_path, [9.5]), specs=specs)
    assert take.status == "ready"
    assert take.provider == "elevenlabs"
    assert take.used_fallback is False


def test_the_measured_duration_is_the_trimmed_one(tmp_path, specs):
    """1.0s of padding around a 9.5s take must not be counted as narration."""
    take = _run(FakeVoice(tmp_path, [9.5]), specs=specs)
    assert take.duration_s == pytest.approx(9.5, abs=0.2)
    assert take.raw_duration_s == pytest.approx(10.5, abs=0.2)


def test_a_short_take_is_re_voiced_with_pauses(tmp_path, specs):
    voice = FakeVoice(tmp_path, [7.5, 9.4])
    take = _run(voice, specs=specs)
    assert take.status == "ready"
    assert take.revoices == 1
    assert PAUSE_TAGS[0] in voice.calls[1][1] or PAUSE_TAGS[1] in voice.calls[1][1]


def test_the_first_attempt_is_never_paced(tmp_path, specs):
    """Pacing is a correction, not a default. An unmeasured line gets none."""
    voice = FakeVoice(tmp_path, [9.5])
    _run(voice, specs=specs)
    assert voice.calls[0][1] == LINE


def test_a_long_take_is_flagged_rather_than_re_rolled(tmp_path, specs):
    """An overrun has no lever on this stack, so it costs nothing to find out.

    Re-rolling was tried and measured on the live CS-1 run of 2026-07-28: four
    blocks came back long, each got two fresh renders, and one of the eight
    landed in window. Roughly $0.25 for a one-second change in runtime — which
    is all an overrun costs, since §6.6 derives block length from the take and
    nothing is centred or compressed any more.

    The two prescribed corrections are both unavailable. `voice_settings.speed`
    is not forwarded by the genblaze ElevenLabs adapter, and shortening the line
    would edit words that `claims.py` has already traced to a fact.
    """
    voice = FakeVoice(tmp_path, [11.5, 10.0])
    take = _run(voice, specs=specs)
    assert take.status == "review"
    assert len(voice.calls) == 1


def test_re_voicing_stops_after_two_attempts(tmp_path, specs):
    voice = FakeVoice(tmp_path, [6.0, 6.0, 6.0, 6.0, 6.0])
    take = _run(voice, specs=specs)
    assert len(voice.calls) == MAX_REVOICES + 1
    assert take.status == "review"


def test_a_block_that_never_lands_keeps_its_closest_take(tmp_path, specs):
    take = _run(FakeVoice(tmp_path, [5.0, 8.7, 6.0]), specs=specs)
    assert take.status == "review"
    assert take.duration_s == pytest.approx(8.7, abs=0.2)


def test_a_dead_primary_completes_on_the_fallback(tmp_path, specs):
    """CS-5's TTS leg. A revoked ElevenLabs key must not stop the run."""
    dead = RuntimeError("401 Unauthorized")
    voice = FakeVoice(tmp_path, [dead, dead, dead, dead, 9.6])
    take = _run(voice, specs=specs)
    assert take.status == "ready"
    assert take.provider == "lmnt"
    assert take.used_fallback is True


def test_the_same_model_is_retried_before_the_provider_switch(tmp_path, specs):
    """A transient 401 should not cost a provider substitution.

    Measured on the video leg: the same GMI key succeeded on the next call about
    half the time. Switching narrator voices for that is a visible downgrade
    bought with a retry that would have cleared.
    """
    voice = FakeVoice(tmp_path, [RuntimeError("Backend error (401)"), 9.5])
    take = _run(voice, specs=specs)
    assert take.provider == "elevenlabs"
    assert [p for p, _ in voice.calls] == ["elevenlabs", "elevenlabs"]


def test_a_permanent_failure_does_not_burn_the_backoff(tmp_path, specs):
    """A 404 will not clear. Retrying it three times only delays the fallback."""
    voice = FakeVoice(tmp_path, [RuntimeError("404 voice not found"), 9.5])
    take = _run(voice, specs=specs)
    assert [p for p, _ in voice.calls] == ["elevenlabs", "lmnt"]


def test_a_fully_dead_chain_fails_closed(tmp_path, specs):
    dead = RuntimeError("401 Unauthorized")
    voice = FakeVoice(tmp_path, [dead] * 12)
    take = _run(voice, specs=specs)
    assert take.status == "failed"
    assert take.uri is None
    assert take.local_path is None


def test_every_attempt_is_recorded(tmp_path, specs):
    """The chain is only an honest claim if the record shows what was tried."""
    voice = FakeVoice(tmp_path, [RuntimeError("401"), 9.5])
    take = _run(voice, specs=specs)
    assert len(take.attempts) == 2
    assert take.attempts[0]["provider"] == "elevenlabs"


def test_cost_accumulates_across_every_attempt(tmp_path, specs):
    """A budget that only counts the take that shipped is not a budget."""
    take = _run(FakeVoice(tmp_path, [5.0, 5.0, 9.6]), specs=specs)
    assert take.cost_usd == pytest.approx(0.09, abs=0.001)


def test_the_fallback_is_never_paced(tmp_path, specs):
    """LMNT has neither audio tags nor a rate knob — a tag would be read aloud."""
    dead = RuntimeError("401")
    voice = FakeVoice(tmp_path, [dead, dead, dead, dead, 6.0, 6.0, 6.0])
    _run(voice, specs=specs)
    lmnt_calls = [text for provider, text in voice.calls if provider == "lmnt"]
    assert all(text == LINE for text in lmnt_calls)


# --- pricing on the direct paths -------------------------------------------
#
# pricing.py registered `ElevenLabs-TTS-v3` at $0.10 — the GMI slug and the GMI
# rate, for a route voice.json says we do not take. Two silent-zero bugs of that
# exact shape were found on 2026-07-28 and both made video look free.


def test_the_direct_elevenlabs_model_is_priced():
    from genblaze_elevenlabs import ElevenLabsTTSProvider

    from newsdesk.pricing import register_all

    provider = ElevenLabsTTSProvider(api_key="test-not-used")
    register_all(elevenlabs=provider)
    assert provider.models.get("eleven_v3").pricing is not None


def test_the_lmnt_model_is_priced():
    from genblaze_lmnt import LMNTProvider

    from newsdesk.pricing import register_all

    provider = LMNTProvider(api_key="test-not-used")
    register_all(lmnt=provider)
    assert provider.models.get("lmnt").pricing is not None


def test_pricing_lmnt_does_not_cost_us_the_voice_alias():
    """The trap under `register_pricing` on a connector with no families.

    LMNT ships an empty registry plus a permissive fallback that carries the
    param contract — `voice_id` → `voice`. `register_pricing` resolves a base
    spec through user layer, then family match, then a BARE ModelSpec — and a
    bare spec registered in the user layer wins over the fallback in `get()`.
    So attaching a rate the obvious way silently drops the alias, `voice_id`
    never reaches the wire, and LMNT reads every line in its default voice
    while the manifest still names Nathan. Same shape as the seedance
    `aspect_ratio`/`ratio` bug: a parameter arriving under a name nothing reads.
    """
    from genblaze_lmnt import LMNTProvider

    from newsdesk.pricing import register_all

    provider = LMNTProvider(api_key="test-not-used")
    register_all(lmnt=provider)
    assert provider.models.get("lmnt").param_aliases.get("voice_id") == "voice"


# --- landing the take in B2 ------------------------------------------------


class FakeStore:
    """Enough of S3StorageBackend to prove the take actually gets written."""

    def __init__(self):
        self.objects: dict[str, bytes] = {}

    def put(self, key: str, data: bytes, content_type: str | None = None) -> None:
        self.objects[key] = data

    def get_durable_url(self, key: str) -> str:
        return f"https://example.invalid/{key}"


def test_a_local_file_url_resolves_to_a_path(tmp_path):
    target = tmp_path / "a take.mp3"
    target.write_bytes(b"x")
    assert local_path_of(target.as_uri()) == target


def test_a_url_that_is_not_a_local_file_is_refused():
    with pytest.raises(NarrationError):
        local_path_of("https://example.invalid/take.mp3")


def test_storing_a_take_uploads_the_trimmed_file(padded):
    store = FakeStore()
    take = Take(n=3, local_path=padded, status="ready", duration_s=9.5)
    stored = store_take(take, prefix="cs1-tower-signal", store=store)
    assert stored.uri == "https://example.invalid/cs1-tower-signal/take-03.wav"
    assert store.objects["cs1-tower-signal/take-03.wav"] == padded.read_bytes()


def test_storing_a_take_records_its_digest(padded):
    stored = store_take(
        Take(n=1, local_path=padded, status="ready"), prefix="p", store=FakeStore()
    )
    assert stored.sha256 == sha256_of(padded)


def test_a_failed_take_is_not_uploaded():
    """A block with no audio must not leave a zero-byte object behind."""
    store = FakeStore()
    stored = store_take(Take(n=1, status="failed"), prefix="p", store=store)
    assert stored.uri is None
    assert store.objects == {}


# --- not talking over ourselves --------------------------------------------


def test_narrate_caps_concurrent_calls(tmp_path, specs):
    """Six blocks at once is how the primary provider gets taken away from us.

    Measured on the live CS-1 run of 2026-07-28: six concurrent ElevenLabs
    calls returned `code=rate_limit` and four of six blocks fell through to
    LMNT. A fallback engaged because we flooded the primary ourselves is not
    resilience — it is a self-inflicted narrator change, disclosed in the
    manifest as if the provider had failed.
    """
    inflight, peak = 0, 0

    async def speak(spec, text):
        nonlocal inflight, peak
        inflight += 1
        peak = max(peak, inflight)
        await asyncio.sleep(0)
        try:
            return _render(tmp_path / f"c{peak}-{inflight}-{len(text)}.wav",
                           [("tone", 9.5)]), 0.01
        finally:
            inflight -= 1

    lines = [(n, LINE) for n in range(1, 7)]
    asyncio.run(narrate(lines, specs=specs, window=(9.0, 10.5), speak=speak,
                        concurrency=2, sleep=_no_wait))
    assert peak <= 2


def test_narrate_returns_a_take_per_block(tmp_path, specs):
    lines = [(n, LINE) for n in range(1, 4)]
    takes = asyncio.run(narrate(lines, specs=specs, window=(9.0, 10.5),
                                speak=FakeVoice(tmp_path, [9.5] * 3), sleep=_no_wait))
    assert [t.n for t in takes] == [1, 2, 3]
